FROM node:18 AS build-stage
WORKDIR /app
RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/suneethabulla/online-ticket-booking.git .

WORKDIR /app/OnlineTicketBookingFrontend
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=build-stage /app/OnlineTicketBookingFrontend/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
